<?php
require('fpdf.php');
$conn = new mysqli("localhost", "root", "", "health_db"); //

if(isset($_GET['id'])){
    $id = intval($_GET['id']);
    $res = $conn->query("SELECT * FROM reports WHERE id = $id");
    $data = $res->fetch_assoc();

    if($data){
        // Initialize PDF with no auto page breaks to prevent splitting
        $pdf = new FPDF();
        $pdf->AddPage();
        $pdf->SetAutoPageBreak(false); 

        // 1. Header Section [cite: 1]
        $pdf->SetFont('Arial','B',18);
        $pdf->SetTextColor(15, 23, 42);
        $pdf->Cell(0, 15, 'MEDSCAN AI - MEDICAL REPORT', 0, 1, 'C');
        $pdf->Line(10, 25, 200, 25);
        $pdf->Ln(5);

        // 2. Patient Info Table [cite: 2]
        $pdf->SetFont('Arial','B',11);
        $pdf->Cell(40, 8, 'Patient Name:', 0);
        $pdf->SetFont('Arial','',11);
        $pdf->Cell(0, 8, $data['patient_name'], 0, 1);

        $pdf->SetFont('Arial','B',11);
        $pdf->Cell(40, 8, 'Report ID:', 0);
        $pdf->SetFont('Arial','',11);
        $pdf->Cell(0, 8, '#' . $data['id'], 0, 1);

        $pdf->SetFont('Arial','B',11);
        $pdf->Cell(40, 8, 'Date:', 0);
        $pdf->SetFont('Arial','',11);
        $pdf->Cell(0, 8, $data['created_at'], 0, 1);
        $pdf->Ln(5);

        // 3. Diagnosis Box (Better Alignment) [cite: 6, 7, 8]
        $pdf->SetFillColor(241, 245, 249);
        $pdf->Rect(10, 60, 190, 35, 'F');
        
        $pdf->SetY(65);
        $pdf->SetFont('Arial','B',12);
        $pdf->Cell(0, 7, 'DIAGNOSIS RESULT', 0, 1, 'C');
        
        $color = ($data['prediction'] == 'NORMAL') ? [39, 174, 96] : [231, 76, 60];
        $pdf->SetTextColor($color[0], $color[1], $color[2]);
        $pdf->SetFont('Arial','B',20);
        $pdf->Cell(0, 12, strtoupper($data['prediction']), 0, 1, 'C');
        
        $pdf->SetTextColor(71, 85, 105);
        $pdf->SetFont('Arial','I',10);
        $pdf->Cell(0, 7, 'AI Confidence Level: ' . number_format($data['confidence'], 2) . '%', 0, 1, 'C');
        $pdf->Ln(10);

        // 4. Image Section (Fixed dimensions to prevent page overflow) [cite: 3]
        $pdf->SetTextColor(0,0,0);
        $pdf->SetFont('Arial','B',11);
        $pdf->Cell(0, 10, 'Analyzed Chest X-Ray:', 0, 1);
        
        $imgY = $pdf->GetY();
        // Calculate dimensions to fit nicely on the remainder of the page
        list($width, $height) = getimagesize($data['image_path']);
        $maxWidth = 90; 
        $displayHeight = ($height / $width) * $maxWidth;
        
        $pdf->Image($data['image_path'], 10, $imgY + 2, $maxWidth);

        // 5. Signature Section (Aligned relative to image) [cite: 5]
        $pdf->SetY($imgY + $displayHeight + 15); 
        $pdf->SetFont('Arial','B',11);
        $pdf->Cell(0, 10, 'Medical Professional Signature:', 0, 1);
        $pdf->Ln(2);
        $pdf->Cell(60, 0, '', 'T'); // Drawing a signature line
        $pdf->Ln(5);

        // 6. Footer (Pinned to bottom of Page 1) 
        $pdf->SetY(-15);
        $pdf->SetFont('Arial','I',8);
        $pdf->SetTextColor(148, 163, 184);
        $pdf->Cell(0, 10, 'This report was generated by MedScan AI and is for screening purposes only.', 0, 0, 'C');

        $pdf->Output('I', 'Report_' . $data['patient_name'] . '.pdf');
    }
}
?>